apiVersion: v1 
kind: Service
metadata:
  name: mongodb-service 
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
      app: mongodb 

---

apiVersion: app/v1
kind: Deployment
metadata:
  name: mongodb-dpl 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb 
    template:
      metadata:
        labels:
          app: mongodb 
        spec:
          containers:
            - name: mongo 
              image: mongo:4.1.8-xerial 
              ports:
                - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value:  
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 
