apiVersion: v1 
kind: Service
metadata:
  name: nodejs-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
      app: nodejs-app 

---

apiVersion: app/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
    template:
      metadata:
        labels:
          app: nodejs-app
        spec:
          containers:
            - name: nodejs 
              image: nodejs 
              ports:
                - containerPort: 8080
