apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-mongo-app
  namespace: argocd
spec:
  project: default
    source: https://github.com/Digital-sam.git
    targetRevision: main
    path: argoCD/Nodejs-Mongoapp
    directory:
      recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: nodejs-mongo-app
    syncPolicy:
      automated:
        prune: false
        selfHeal: true
    sourceType: Directory
    sync:
      comparedTo:
        destination:
          namespace:
          server: https://kubernetes.default.svc
        source: 
          path: argoCD/Nodejs-Mongoapp
          repoURL: https://github.com/Digital-sam.git
          targetRevision: main
